### ISSUE TITLE
Typo: same for enum (english or french)

### ISSUE THREAD

**Issue by houssenedao** [CreativeTeamCi/cilogos#2]
You have to be a bit coherent, either your tables are in French or in English not both at the same time.

https://github.com/CreativeTeamCi/cilogos/blob/8022c5a1ff21b98a566dd64ec3e05e897ecad7ca/database/migrations/2020_11_29_105055_create_business_logos_table.php#L26

**Comment by sanamichael** [comment]
Fixed
